name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix: { dir: [ "2015", "2016", "2017", "2018", "2019", "2020", "2022", "2023" ] }

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.PAT_TOKEN }}
    - name: Build
      run: cargo build --verbose
      working-directory: ${{ matrix.dir }}
    - name: Run linter
      run: cargo clippy -- -D warnings
      working-directory: ${{ matrix.dir }}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{ matrix.dir }}
